### PR TITLE
Setup Sequelize ORM

### PR DESCRIPTION
**Pull request by Alpha1202**
#### What does this PR do?
- Setup Sequelize ORM

#### Description of Task to be completed?
- update gitignore file
- add .sequelizerc file
- installed some neccessary dependencies
- add .github folder for PR template
- refactored index.js file
- add config.js for sequelize
- add model and migration files

#### How should this be manually tested?
- clone this branch
- run npm install

#### Any background context you want to provide?
- N/A

#### What are the relevant pivotal tracker stories?
- [169177081](https://www.pivotaltracker.com/story/show/169177081)

#### Screenshots (if appropriate)
- N/A

#### Questions:
- N/A

### CODE REVIEW

**Review by Ileriayo — COMMENTED** [review]
Good stuff!

However, I noticed a lot of `require` and `module.exports`. How about using >= ES6 ?
What do you say?

**Review by codexempire — APPROVED** [review]
Nice work but will like to know the value of the is production and isTest variables within the `config.js` as this could the manipulated better another way

**Comment by Alpha1202** [comment]
> Good stuff!
> 
> However, I noticed a lot of `require` and `module.exports`. How about using >= ES6 ?
> What do you say?

Ok, can I be permitted to fix it in my next PR

**Comment by Alpha1202** [comment]
> Nice work but will like to know the value of the is production and isTest variables within the `config.js` as this could the manipulated better another way

Ok, I check on you via slack

**Pull request merged**
